//error
try{
    console.log(a);
}catch(err){
    console.log("something went wrong"); //err also we can use
} 